/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerificarRouteImport } from './routes/verificar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotificacionesRouteImport } from './routes/_authenticated/notificaciones'
import { Route as AuthenticatedMisPuntuacionesRouteImport } from './routes/_authenticated/mis-puntuaciones'
import { Route as AuthenticatedMapaRouteImport } from './routes/_authenticated/mapa'
import { Route as AuthenticatedInicioRouteImport } from './routes/_authenticated/inicio'
import { Route as AuthenticatedGuardadosRouteImport } from './routes/_authenticated/guardados'
import { Route as AuthenticatedExplorarRouteImport } from './routes/_authenticated/explorar'
import { Route as AuthenticatedCrearRouteImport } from './routes/_authenticated/crear'
import { Route as AuthenticatedBuscarRouteImport } from './routes/_authenticated/buscar'
import { Route as AuthenticatedAmigosRouteImport } from './routes/_authenticated/amigos'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedUUsernameRouteImport } from './routes/_authenticated/u.$username'
import { Route as AuthenticatedPointIdRouteImport } from './routes/_authenticated/point.$id'

const VerificarRoute = VerificarRouteImport.update({
  id: '/verificar',
  path: '/verificar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificacionesRoute =
  AuthenticatedNotificacionesRouteImport.update({
    id: '/notificaciones',
    path: '/notificaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMisPuntuacionesRoute =
  AuthenticatedMisPuntuacionesRouteImport.update({
    id: '/mis-puntuaciones',
    path: '/mis-puntuaciones',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMapaRoute = AuthenticatedMapaRouteImport.update({
  id: '/mapa',
  path: '/mapa',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInicioRoute = AuthenticatedInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuardadosRoute = AuthenticatedGuardadosRouteImport.update({
  id: '/guardados',
  path: '/guardados',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExplorarRoute = AuthenticatedExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrearRoute = AuthenticatedCrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBuscarRoute = AuthenticatedBuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAmigosRoute = AuthenticatedAmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUUsernameRoute = AuthenticatedUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPointIdRoute = AuthenticatedPointIdRouteImport.update({
  id: '/point/$id',
  path: '/point/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/verificar': typeof VerificarRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/crear': typeof AuthenticatedCrearRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/guardados': typeof AuthenticatedGuardadosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mis-puntuaciones': typeof AuthenticatedMisPuntuacionesRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/point/$id': typeof AuthenticatedPointIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/verificar': typeof VerificarRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/amigos': typeof AuthenticatedAmigosRoute
  '/buscar': typeof AuthenticatedBuscarRoute
  '/crear': typeof AuthenticatedCrearRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/guardados': typeof AuthenticatedGuardadosRoute
  '/inicio': typeof AuthenticatedInicioRoute
  '/mapa': typeof AuthenticatedMapaRoute
  '/mis-puntuaciones': typeof AuthenticatedMisPuntuacionesRoute
  '/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/point/$id': typeof AuthenticatedPointIdRoute
  '/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/verificar': typeof VerificarRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/amigos': typeof AuthenticatedAmigosRoute
  '/_authenticated/buscar': typeof AuthenticatedBuscarRoute
  '/_authenticated/crear': typeof AuthenticatedCrearRoute
  '/_authenticated/explorar': typeof AuthenticatedExplorarRoute
  '/_authenticated/guardados': typeof AuthenticatedGuardadosRoute
  '/_authenticated/inicio': typeof AuthenticatedInicioRoute
  '/_authenticated/mapa': typeof AuthenticatedMapaRoute
  '/_authenticated/mis-puntuaciones': typeof AuthenticatedMisPuntuacionesRoute
  '/_authenticated/notificaciones': typeof AuthenticatedNotificacionesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/point/$id': typeof AuthenticatedPointIdRoute
  '/_authenticated/u/$username': typeof AuthenticatedUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/registro'
    | '/verificar'
    | '/admin'
    | '/amigos'
    | '/buscar'
    | '/crear'
    | '/explorar'
    | '/guardados'
    | '/inicio'
    | '/mapa'
    | '/mis-puntuaciones'
    | '/notificaciones'
    | '/perfil'
    | '/point/$id'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/registro'
    | '/verificar'
    | '/admin'
    | '/amigos'
    | '/buscar'
    | '/crear'
    | '/explorar'
    | '/guardados'
    | '/inicio'
    | '/mapa'
    | '/mis-puntuaciones'
    | '/notificaciones'
    | '/perfil'
    | '/point/$id'
    | '/u/$username'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/registro'
    | '/verificar'
    | '/_authenticated/admin'
    | '/_authenticated/amigos'
    | '/_authenticated/buscar'
    | '/_authenticated/crear'
    | '/_authenticated/explorar'
    | '/_authenticated/guardados'
    | '/_authenticated/inicio'
    | '/_authenticated/mapa'
    | '/_authenticated/mis-puntuaciones'
    | '/_authenticated/notificaciones'
    | '/_authenticated/perfil'
    | '/_authenticated/point/$id'
    | '/_authenticated/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
  VerificarRoute: typeof VerificarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verificar': {
      id: '/verificar'
      path: '/verificar'
      fullPath: '/verificar'
      preLoaderRoute: typeof VerificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificaciones': {
      id: '/_authenticated/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof AuthenticatedNotificacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mis-puntuaciones': {
      id: '/_authenticated/mis-puntuaciones'
      path: '/mis-puntuaciones'
      fullPath: '/mis-puntuaciones'
      preLoaderRoute: typeof AuthenticatedMisPuntuacionesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/mapa': {
      id: '/_authenticated/mapa'
      path: '/mapa'
      fullPath: '/mapa'
      preLoaderRoute: typeof AuthenticatedMapaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inicio': {
      id: '/_authenticated/inicio'
      path: '/inicio'
      fullPath: '/inicio'
      preLoaderRoute: typeof AuthenticatedInicioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guardados': {
      id: '/_authenticated/guardados'
      path: '/guardados'
      fullPath: '/guardados'
      preLoaderRoute: typeof AuthenticatedGuardadosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explorar': {
      id: '/_authenticated/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AuthenticatedExplorarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crear': {
      id: '/_authenticated/crear'
      path: '/crear'
      fullPath: '/crear'
      preLoaderRoute: typeof AuthenticatedCrearRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/buscar': {
      id: '/_authenticated/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof AuthenticatedBuscarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/amigos': {
      id: '/_authenticated/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AuthenticatedAmigosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/u/$username': {
      id: '/_authenticated/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof AuthenticatedUUsernameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/point/$id': {
      id: '/_authenticated/point/$id'
      path: '/point/$id'
      fullPath: '/point/$id'
      preLoaderRoute: typeof AuthenticatedPointIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAmigosRoute: typeof AuthenticatedAmigosRoute
  AuthenticatedBuscarRoute: typeof AuthenticatedBuscarRoute
  AuthenticatedCrearRoute: typeof AuthenticatedCrearRoute
  AuthenticatedExplorarRoute: typeof AuthenticatedExplorarRoute
  AuthenticatedGuardadosRoute: typeof AuthenticatedGuardadosRoute
  AuthenticatedInicioRoute: typeof AuthenticatedInicioRoute
  AuthenticatedMapaRoute: typeof AuthenticatedMapaRoute
  AuthenticatedMisPuntuacionesRoute: typeof AuthenticatedMisPuntuacionesRoute
  AuthenticatedNotificacionesRoute: typeof AuthenticatedNotificacionesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedPointIdRoute: typeof AuthenticatedPointIdRoute
  AuthenticatedUUsernameRoute: typeof AuthenticatedUUsernameRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAmigosRoute: AuthenticatedAmigosRoute,
  AuthenticatedBuscarRoute: AuthenticatedBuscarRoute,
  AuthenticatedCrearRoute: AuthenticatedCrearRoute,
  AuthenticatedExplorarRoute: AuthenticatedExplorarRoute,
  AuthenticatedGuardadosRoute: AuthenticatedGuardadosRoute,
  AuthenticatedInicioRoute: AuthenticatedInicioRoute,
  AuthenticatedMapaRoute: AuthenticatedMapaRoute,
  AuthenticatedMisPuntuacionesRoute: AuthenticatedMisPuntuacionesRoute,
  AuthenticatedNotificacionesRoute: AuthenticatedNotificacionesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedPointIdRoute: AuthenticatedPointIdRoute,
  AuthenticatedUUsernameRoute: AuthenticatedUUsernameRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
  VerificarRoute: VerificarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
